language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_deploy:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: ./dist
  on:
    branch: master
after_deploy:
  - npm run travis-deploy-once "npm run semantic-release"
